
name: Pruebas de API con Newman


on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Newman y el Reporter htmlextra
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Crear archivo de datos desde el secreto
        run: |
          mkdir -p postman # Asegura que la carpeta exista
          echo "${{ secrets.DATA_CSV_CONTENT }}" > postman/data.csv
          
          # Paso de verificación para depuración: Muestra el contenido del archivo creado
          echo "--- Contenido de data.csv creado ---"
          cat postman/data.csv
          echo "------------------------------------"

      - name: Ejecutar Pruebas de API y Generar Reporte
        run: |
          newman run "postman/Prueba_Davivienda.postman_collection.json" \
            -e "postman/Davivienda_Env.postman_environment.json" \
            -d "postman/data.csv" \
            -r cli,htmlextra \
            --reporter-htmlextra-export "newman-report/report.html" \
            --env-var "admin_username=${{ secrets.HRM_USERNAME }}" \
            --env-var "admin_password=${{ secrets.HRM_PASSWORD }}"


      - name: Subir artefacto del reporte
        uses: actions/upload-pages-artifact@v3
        with:
          path: './newman-report'

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4