name: Pruebas de API con Newman
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del cÃ³digo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Newman y el Reporter htmlextra
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Crear archivo de datos desde el secreto
        run: |
          mkdir -p postman
          echo "${{ secrets.DATA_CSV_CONTENT }}" > postman/data.csv

      - name: Ejecutar Pruebas de Newman
        run: |
          newman run "postman/Collection_Davi.json" \
            -e "postman/Environment_Davi.json" \
            -d "postman/data.csv" \
            -r cli,htmlextra \
            --reporter-htmlextra-export "report/index.html" \
            --env-var "admin_username=${{ secrets.HRM_USERNAME }}" \
            --env-var "admin_password=${{ secrets.HRM_PASSWORD }}"
      
      - name: Subir artefacto del reporte para el despliegue
        uses: actions/upload-pages-artifact@v3
        with:

          path: 'report/'

  deploy:
    needs: run-newman-tests
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4